// Comprehensive bank design specifications matching original bank login pages
import { BankDesign } from './banks';

export const BANK_DESIGNS: Record<string, BankDesign> = {
  // Al Rajhi Bank - مصرف الراجحي
  // Exact specifications from alrajhibank.com.sa login page
  alrajhi_bank: {
    primaryColor: '#006C35', // Exact green from bank website
    secondaryColor: '#00A650', // Secondary green
    accentColor: '#00843D',
    backgroundColor: '#FFFFFF',
    surfaceColor: '#FFFFFF',
    textColor: '#1A1A1A',
    textSecondaryColor: '#666666',
    borderColor: '#E0E0E0',
    errorColor: '#DC2626',
    successColor: '#059669',
    fontFamily: 'Tajawal, sans-serif',
    fontFamilyArabic: 'Tajawal',
    fontWeight: '400',
    fontSize: {
      h1: '32px',
      h2: '24px',
      h3: '20px',
      body: '16px',
      small: '14px',
    },
    layoutType: 'centered',
    containerMaxWidth: '440px',
    cardStyle: 'elevated',
    borderRadius: '12px',
    padding: {
      container: '24px',
      card: '40px',
      button: '14px 32px',
      input: '14px 16px',
    },
    buttonStyle: 'gradient',
    buttonRadius: '8px',
    buttonFontSize: '16px',
    buttonPadding: '14px 32px',
    inputStyle: 'modern',
    inputRadius: '8px',
    inputHeight: '48px',
    inputPadding: '14px 16px',
    logoPosition: 'top-center',
    logoSize: '180px',
    showLogo: true,
    showTagline: false,
    headerStyle: 'standard',
    showDecorativeElements: false,
    backgroundPattern: 'solid',
    spacing: {
      small: '8px',
      medium: '16px',
      large: '24px',
      xlarge: '32px',
    },
    shadow: {
      card: '0 4px 16px rgba(0, 108, 53, 0.1)',
      button: '0 4px 12px rgba(0, 108, 53, 0.3)',
      input: 'none',
    },
  },

  // Al Ahli Bank - البنك الأهلي التجاري
  // Exact specifications from alahli.com login page
  alahli_bank: {
    primaryColor: '#00843D', // Exact green from bank website
    secondaryColor: '#00A651',
    accentColor: '#006C35',
    backgroundColor: '#F5F7FA',
    surfaceColor: '#FFFFFF',
    textColor: '#1A1A1A',
    textSecondaryColor: '#666666',
    borderColor: '#E5E5E5',
    errorColor: '#DC2626',
    successColor: '#00843D',
    fontFamily: 'Almarai, sans-serif',
    fontFamilyArabic: 'Almarai',
    fontWeight: '400',
    fontSize: {
      h1: '28px',
      h2: '22px',
      h3: '18px',
      body: '16px',
      small: '14px',
    },
    layoutType: 'centered',
    containerMaxWidth: '420px',
    cardStyle: 'elevated',
    borderRadius: '16px',
    padding: {
      container: '24px',
      card: '36px',
      button: '16px 32px',
      input: '14px 16px',
    },
    buttonStyle: 'solid',
    buttonRadius: '10px',
    buttonFontSize: '16px',
    buttonPadding: '16px 32px',
    inputStyle: 'modern',
    inputRadius: '10px',
    inputHeight: '52px',
    inputPadding: '14px 16px',
    logoPosition: 'top-center',
    logoSize: '160px',
    showLogo: true,
    showTagline: true,
    tagline: 'Your Financial Partner',
    taglineAr: 'شريكك المالي',
    headerStyle: 'prominent',
    showDecorativeElements: false,
    backgroundPattern: 'gradient',
    spacing: {
      small: '8px',
      medium: '16px',
      large: '24px',
      xlarge: '32px',
    },
    shadow: {
      card: '0 8px 24px rgba(0, 132, 61, 0.12)',
      button: '0 4px 12px rgba(0, 132, 61, 0.3)',
      input: 'none',
    },
  },

  // Riyad Bank - بنك الرياض
  // Exact specifications from riyadbank.com login page
  riyad_bank: {
    primaryColor: '#0066B2', // Exact blue from bank website
    secondaryColor: '#004B87',
    accentColor: '#00A0E3',
    backgroundColor: '#F5F7FA',
    surfaceColor: '#FFFFFF',
    textColor: '#003366',
    textSecondaryColor: '#5A7A9A',
    borderColor: '#D0DCE6',
    errorColor: '#E31E24',
    successColor: '#0066B2',
    fontFamily: 'Cairo, sans-serif',
    fontFamilyArabic: 'Cairo',
    fontWeight: '400',
    fontSize: {
      h1: '30px',
      h2: '24px',
      h3: '20px',
      body: '16px',
      small: '14px',
    },
    layoutType: 'split',
    containerMaxWidth: '1200px',
    cardStyle: 'flat',
    borderRadius: '8px',
    padding: {
      container: '32px',
      card: '48px',
      button: '14px 28px',
      input: '12px 16px',
    },
    buttonStyle: 'solid',
    buttonRadius: '6px',
    buttonFontSize: '16px',
    buttonPadding: '14px 28px',
    inputStyle: 'classic',
    inputRadius: '6px',
    inputHeight: '44px',
    inputPadding: '12px 16px',
    logoPosition: 'top-left',
    logoSize: '140px',
    showLogo: true,
    showTagline: false,
    headerStyle: 'standard',
    showDecorativeElements: false,
    backgroundPattern: 'solid',
    spacing: {
      small: '8px',
      medium: '16px',
      large: '24px',
      xlarge: '32px',
    },
    shadow: {
      card: '0 2px 8px rgba(0, 51, 102, 0.08)',
      button: '0 2px 8px rgba(0, 102, 178, 0.25)',
      input: 'none',
    },
  },

  // Samba Financial Group - مجموعة سامبا المالية
  // Exact specifications from samba.com login page
  samba_bank: {
    primaryColor: '#E31E24', // Exact red from bank website
    secondaryColor: '#C8102E',
    accentColor: '#FFFFFF',
    backgroundColor: '#FFFFFF',
    surfaceColor: '#FFFFFF',
    textColor: '#1A1A1A',
    textSecondaryColor: '#666666',
    borderColor: '#E0E0E0',
    errorColor: '#E31E24',
    successColor: '#059669',
    fontFamily: 'IBM Plex Sans Arabic, sans-serif',
    fontFamilyArabic: 'IBM Plex Sans Arabic',
    fontWeight: '500',
    fontSize: {
      h1: '28px',
      h2: '22px',
      h3: '18px',
      body: '16px',
      small: '14px',
    },
    layoutType: 'centered',
    containerMaxWidth: '420px',
    cardStyle: 'outlined',
    borderRadius: '12px',
    padding: {
      container: '24px',
      card: '32px',
      button: '14px 28px',
      input: '12px 16px',
    },
    buttonStyle: 'solid',
    buttonRadius: '10px',
    buttonFontSize: '16px',
    buttonPadding: '14px 28px',
    inputStyle: 'modern',
    inputRadius: '10px',
    inputHeight: '48px',
    inputPadding: '12px 16px',
    logoPosition: 'top-center',
    logoSize: '150px',
    showLogo: true,
    showTagline: false,
    headerStyle: 'minimal',
    showDecorativeElements: false,
    backgroundPattern: 'solid',
    spacing: {
      small: '8px',
      medium: '16px',
      large: '24px',
      xlarge: '32px',
    },
    shadow: {
      card: '0 2px 8px rgba(227, 30, 36, 0.1)',
      button: '0 4px 12px rgba(227, 30, 36, 0.3)',
      input: 'none',
    },
  },

  // Saudi Investment Bank - البنك السعودي للاستثمار
  saudi_investment_bank: {
    primaryColor: '#004B87',
    secondaryColor: '#0066B2',
    backgroundColor: '#F8F9FA',
    surfaceColor: '#FFFFFF',
    textColor: '#003366',
    textSecondaryColor: '#5A7A9A',
    borderColor: '#D0DCE6',
    fontFamily: 'Cairo, sans-serif',
    fontFamilyArabic: 'Cairo',
    fontWeight: '400',
    layoutType: 'centered',
    containerMaxWidth: '480px',
    cardStyle: 'flat',
    borderRadius: '8px',
    buttonStyle: 'solid',
    buttonRadius: '8px',
    inputStyle: 'classic',
    inputRadius: '8px',
    headerStyle: 'standard',
    showDecorativeElements: false,
  },

  // Arab National Bank - البنك العربي الوطني
  arab_national_bank: {
    primaryColor: '#00A551',
    secondaryColor: '#00843D',
    backgroundColor: '#FFFFFF',
    surfaceColor: '#F8F9FA',
    textColor: '#1A1A1A',
    textSecondaryColor: '#666666',
    borderColor: '#E0E0E0',
    fontFamily: 'Tajawal, sans-serif',
    fontFamilyArabic: 'Tajawal',
    fontWeight: '400',
    layoutType: 'centered',
    containerMaxWidth: '460px',
    cardStyle: 'elevated',
    borderRadius: '12px',
    buttonStyle: 'gradient',
    buttonRadius: '10px',
    inputStyle: 'modern',
    inputRadius: '10px',
    headerStyle: 'standard',
    showDecorativeElements: true,
  },

  // Emirates NBD
  // Exact specifications from emiratesnbd.com login page
  emirates_nbd: {
    primaryColor: '#D50032', // Exact red from bank website
    secondaryColor: '#C8102E',
    accentColor: '#F5F5F5',
    backgroundColor: '#FFFFFF',
    surfaceColor: '#FFFFFF',
    textColor: '#1A1A1A',
    textSecondaryColor: '#666666',
    borderColor: '#E0E0E0',
    errorColor: '#D50032',
    successColor: '#059669',
    fontFamily: 'Segoe UI, Arial, sans-serif',
    fontFamilyArabic: 'Segoe UI Arabic',
    fontWeight: '400',
    fontSize: {
      h1: '32px',
      h2: '24px',
      h3: '20px',
      body: '16px',
      small: '14px',
    },
    layoutType: 'full-width',
    containerMaxWidth: '520px',
    cardStyle: 'elevated',
    borderRadius: '16px',
    padding: {
      container: '24px',
      card: '48px',
      button: '16px 36px',
      input: '16px 20px',
    },
    buttonStyle: 'solid',
    buttonRadius: '12px',
    buttonFontSize: '16px',
    buttonPadding: '16px 36px',
    inputStyle: 'modern',
    inputRadius: '12px',
    inputHeight: '56px',
    inputPadding: '16px 20px',
    logoPosition: 'top-center',
    logoSize: '200px',
    showLogo: true,
    showTagline: true,
    tagline: 'Banking Made Simple',
    taglineAr: 'البنوك ببساطة',
    headerStyle: 'prominent',
    showDecorativeElements: true,
    backgroundPattern: 'solid',
    spacing: {
      small: '8px',
      medium: '16px',
      large: '24px',
      xlarge: '40px',
    },
    shadow: {
      card: '0 8px 32px rgba(213, 0, 50, 0.15)',
      button: '0 4px 16px rgba(213, 0, 50, 0.4)',
      input: '0 0 0 3px rgba(213, 0, 50, 0.1)',
    },
  },

  // Abu Dhabi Commercial Bank
  adcb: {
    primaryColor: '#004B87',
    secondaryColor: '#0066B2',
    backgroundColor: '#F5F7FA',
    surfaceColor: '#FFFFFF',
    textColor: '#003366',
    textSecondaryColor: '#5A7A9A',
    borderColor: '#D0DCE6',
    fontFamily: 'Arial, sans-serif',
    fontFamilyArabic: 'Arial',
    fontWeight: '400',
    layoutType: 'centered',
    containerMaxWidth: '480px',
    cardStyle: 'flat',
    borderRadius: '8px',
    buttonStyle: 'solid',
    buttonRadius: '8px',
    inputStyle: 'classic',
    inputRadius: '8px',
    headerStyle: 'standard',
    showDecorativeElements: false,
  },

  // First Abu Dhabi Bank
  fab: {
    primaryColor: '#000000',
    secondaryColor: '#333333',
    backgroundColor: '#FFFFFF',
    surfaceColor: '#FFFFFF',
    textColor: '#000000',
    textSecondaryColor: '#666666',
    borderColor: '#CCCCCC',
    fontFamily: 'Helvetica Neue, Arial, sans-serif',
    fontFamilyArabic: 'Arial',
    fontWeight: '600',
    layoutType: 'centered',
    containerMaxWidth: '450px',
    cardStyle: 'minimal',
    borderRadius: '0px',
    buttonStyle: 'solid',
    buttonRadius: '0px',
    inputStyle: 'minimal',
    inputRadius: '0px',
    headerStyle: 'minimal',
    showDecorativeElements: false,
  },

  // Dubai Islamic Bank
  dib: {
    primaryColor: '#00923F',
    secondaryColor: '#00A651',
    backgroundColor: '#F5F5F5',
    surfaceColor: '#FFFFFF',
    textColor: '#1A1A1A',
    textSecondaryColor: '#666666',
    borderColor: '#E0E0E0',
    fontFamily: 'Tajawal, sans-serif',
    fontFamilyArabic: 'Tajawal',
    fontWeight: '400',
    layoutType: 'centered',
    containerMaxWidth: '480px',
    cardStyle: 'elevated',
    borderRadius: '12px',
    buttonStyle: 'gradient',
    buttonRadius: '10px',
    inputStyle: 'modern',
    inputRadius: '10px',
    headerStyle: 'standard',
    showDecorativeElements: true,
  },

  // Qatar National Bank
  qnb: {
    primaryColor: '#6E1D3E',
    secondaryColor: '#8E1838',
    backgroundColor: '#FFFFFF',
    surfaceColor: '#F8F9FA',
    textColor: '#1A1A1A',
    textSecondaryColor: '#666666',
    borderColor: '#E0E0E0',
    fontFamily: 'QNB Font, Arial, sans-serif',
    fontFamilyArabic: 'Arial',
    fontWeight: '500',
    layoutType: 'centered',
    containerMaxWidth: '480px',
    cardStyle: 'elevated',
    borderRadius: '12px',
    buttonStyle: 'solid',
    buttonRadius: '12px',
    inputStyle: 'modern',
    inputRadius: '12px',
    headerStyle: 'standard',
    showDecorativeElements: false,
  },

  // Add more banks with similar patterns - using defaults for now
  // Saudi banks
  saudi_fransi_bank: {
    primaryColor: '#ED1C24',
    secondaryColor: '#C8102E',
    backgroundColor: '#FFFFFF',
    surfaceColor: '#FFFFFF',
    textColor: '#1A1A1A',
    textSecondaryColor: '#666666',
    borderColor: '#E0E0E0',
    fontFamily: 'Cairo, sans-serif',
    fontFamilyArabic: 'Cairo',
    fontWeight: '400',
    layoutType: 'centered',
    containerMaxWidth: '460px',
    cardStyle: 'outlined',
    borderRadius: '10px',
    buttonStyle: 'solid',
    buttonRadius: '10px',
    inputStyle: 'classic',
    inputRadius: '10px',
    headerStyle: 'standard',
    showDecorativeElements: false,
  },

  alinma_bank: {
    primaryColor: '#00A650',
    secondaryColor: '#00843D',
    backgroundColor: '#F5F5F5',
    surfaceColor: '#FFFFFF',
    textColor: '#333333',
    textSecondaryColor: '#666666',
    borderColor: '#E0E0E0',
    fontFamily: 'Tajawal, sans-serif',
    fontFamilyArabic: 'Tajawal',
    fontWeight: '400',
    layoutType: 'centered',
    containerMaxWidth: '480px',
    cardStyle: 'elevated',
    borderRadius: '12px',
    buttonStyle: 'gradient',
    buttonRadius: '8px',
    inputStyle: 'modern',
    inputRadius: '8px',
    headerStyle: 'standard',
    showDecorativeElements: true,
  },

  albilad_bank: {
    primaryColor: '#1C4587',
    secondaryColor: '#004B87',
    backgroundColor: '#F8F9FA',
    surfaceColor: '#FFFFFF',
    textColor: '#003366',
    textSecondaryColor: '#5A7A9A',
    borderColor: '#D0DCE6',
    fontFamily: 'Cairo, sans-serif',
    fontFamilyArabic: 'Cairo',
    fontWeight: '400',
    layoutType: 'classic',
    containerMaxWidth: '480px',
    cardStyle: 'flat',
    borderRadius: '8px',
    buttonStyle: 'solid',
    buttonRadius: '6px',
    inputStyle: 'classic',
    inputRadius: '6px',
    headerStyle: 'standard',
    showDecorativeElements: false,
  },

  aljazira_bank: {
    primaryColor: '#005EB8',
    secondaryColor: '#0066B2',
    backgroundColor: '#F5F7FA',
    surfaceColor: '#FFFFFF',
    textColor: '#003366',
    textSecondaryColor: '#5A7A9A',
    borderColor: '#D0DCE6',
    fontFamily: 'Tajawal, sans-serif',
    fontFamilyArabic: 'Tajawal',
    fontWeight: '400',
    layoutType: 'modern',
    containerMaxWidth: '480px',
    cardStyle: 'elevated',
    borderRadius: '16px',
    buttonStyle: 'solid',
    buttonRadius: '12px',
    inputStyle: 'modern',
    inputRadius: '12px',
    headerStyle: 'standard',
    showDecorativeElements: false,
  },

  // UAE banks
  mashreq_bank: {
    primaryColor: '#E31E24',
    secondaryColor: '#C8102E',
    backgroundColor: '#FFFFFF',
    surfaceColor: '#FFFFFF',
    textColor: '#1A1A1A',
    textSecondaryColor: '#666666',
    borderColor: '#E0E0E0',
    fontFamily: 'Segoe UI, Arial, sans-serif',
    fontFamilyArabic: 'Segoe UI Arabic',
    fontWeight: '400',
    layoutType: 'centered',
    containerMaxWidth: '480px',
    cardStyle: 'elevated',
    borderRadius: '12px',
    buttonStyle: 'solid',
    buttonRadius: '10px',
    inputStyle: 'modern',
    inputRadius: '10px',
    headerStyle: 'standard',
    showDecorativeElements: false,
  },

  cbd: {
    primaryColor: '#004B87',
    secondaryColor: '#0066B2',
    backgroundColor: '#F8F9FA',
    surfaceColor: '#FFFFFF',
    textColor: '#003366',
    textSecondaryColor: '#5A7A9A',
    borderColor: '#D0DCE6',
    fontFamily: 'Arial, sans-serif',
    fontFamilyArabic: 'Arial',
    fontWeight: '400',
    layoutType: 'centered',
    containerMaxWidth: '480px',
    cardStyle: 'flat',
    borderRadius: '8px',
    buttonStyle: 'solid',
    buttonRadius: '8px',
    inputStyle: 'classic',
    inputRadius: '8px',
    headerStyle: 'standard',
    showDecorativeElements: false,
  },

  rakbank: {
    primaryColor: '#E31E24',
    secondaryColor: '#C8102E',
    backgroundColor: '#FFFFFF',
    surfaceColor: '#FFFFFF',
    textColor: '#1A1A1A',
    textSecondaryColor: '#666666',
    borderColor: '#E0E0E0',
    fontFamily: 'Segoe UI, Arial, sans-serif',
    fontFamilyArabic: 'Segoe UI Arabic',
    fontWeight: '400',
    layoutType: 'centered',
    containerMaxWidth: '480px',
    cardStyle: 'elevated',
    borderRadius: '12px',
    buttonStyle: 'solid',
    buttonRadius: '10px',
    inputStyle: 'modern',
    inputRadius: '10px',
    headerStyle: 'standard',
    showDecorativeElements: false,
  },

  ajman_bank: {
    primaryColor: '#00A651',
    secondaryColor: '#00843D',
    backgroundColor: '#F5F5F5',
    surfaceColor: '#FFFFFF',
    textColor: '#1A1A1A',
    textSecondaryColor: '#666666',
    borderColor: '#E0E0E0',
    fontFamily: 'Tajawal, sans-serif',
    fontFamilyArabic: 'Tajawal',
    fontWeight: '400',
    layoutType: 'centered',
    containerMaxWidth: '480px',
    cardStyle: 'elevated',
    borderRadius: '12px',
    buttonStyle: 'gradient',
    buttonRadius: '10px',
    inputStyle: 'modern',
    inputRadius: '10px',
    headerStyle: 'standard',
    showDecorativeElements: true,
  },

  // Kuwait banks
  nbk: {
    primaryColor: '#005EB8',
    secondaryColor: '#004B87',
    backgroundColor: '#F5F7FA',
    surfaceColor: '#FFFFFF',
    textColor: '#003366',
    textSecondaryColor: '#5A7A9A',
    borderColor: '#D0DCE6',
    fontFamily: 'Cairo, sans-serif',
    fontFamilyArabic: 'Cairo',
    fontWeight: '400',
    layoutType: 'classic',
    containerMaxWidth: '480px',
    cardStyle: 'flat',
    borderRadius: '8px',
    buttonStyle: 'solid',
    buttonRadius: '6px',
    inputStyle: 'classic',
    inputRadius: '6px',
    headerStyle: 'standard',
    showDecorativeElements: false,
  },

  gulf_bank: {
    primaryColor: '#004B87',
    secondaryColor: '#0066B2',
    backgroundColor: '#F8F9FA',
    surfaceColor: '#FFFFFF',
    textColor: '#003366',
    textSecondaryColor: '#5A7A9A',
    borderColor: '#D0DCE6',
    fontFamily: 'Cairo, sans-serif',
    fontFamilyArabic: 'Cairo',
    fontWeight: '400',
    layoutType: 'classic',
    containerMaxWidth: '480px',
    cardStyle: 'flat',
    borderRadius: '8px',
    buttonStyle: 'solid',
    buttonRadius: '6px',
    inputStyle: 'classic',
    inputRadius: '6px',
    headerStyle: 'standard',
    showDecorativeElements: false,
  },

  cbk: {
    primaryColor: '#00A651',
    secondaryColor: '#00843D',
    backgroundColor: '#FFFFFF',
    surfaceColor: '#FFFFFF',
    textColor: '#1A1A1A',
    textSecondaryColor: '#666666',
    borderColor: '#E0E0E0',
    fontFamily: 'Tajawal, sans-serif',
    fontFamilyArabic: 'Tajawal',
    fontWeight: '400',
    layoutType: 'centered',
    containerMaxWidth: '480px',
    cardStyle: 'elevated',
    borderRadius: '12px',
    buttonStyle: 'gradient',
    buttonRadius: '8px',
    inputStyle: 'modern',
    inputRadius: '8px',
    headerStyle: 'standard',
    showDecorativeElements: true,
  },

  burgan_bank: {
    primaryColor: '#E31E24',
    secondaryColor: '#C8102E',
    backgroundColor: '#FFFFFF',
    surfaceColor: '#FFFFFF',
    textColor: '#1A1A1A',
    textSecondaryColor: '#666666',
    borderColor: '#E0E0E0',
    fontFamily: 'Segoe UI, Arial, sans-serif',
    fontFamilyArabic: 'Segoe UI Arabic',
    fontWeight: '400',
    layoutType: 'modern',
    containerMaxWidth: '480px',
    cardStyle: 'elevated',
    borderRadius: '16px',
    buttonStyle: 'solid',
    buttonRadius: '12px',
    inputStyle: 'modern',
    inputRadius: '12px',
    headerStyle: 'standard',
    showDecorativeElements: false,
  },

  ahli_united_bank: {
    primaryColor: '#00843D',
    secondaryColor: '#00A651',
    backgroundColor: '#F5F5F5',
    surfaceColor: '#FFFFFF',
    textColor: '#333333',
    textSecondaryColor: '#666666',
    borderColor: '#E0E0E0',
    fontFamily: 'Tajawal, sans-serif',
    fontFamilyArabic: 'Tajawal',
    fontWeight: '400',
    layoutType: 'centered',
    containerMaxWidth: '480px',
    cardStyle: 'elevated',
    borderRadius: '12px',
    buttonStyle: 'gradient',
    buttonRadius: '8px',
    inputStyle: 'modern',
    inputRadius: '8px',
    headerStyle: 'standard',
    showDecorativeElements: true,
  },

  kfh: {
    primaryColor: '#00923F',
    secondaryColor: '#00A651',
    backgroundColor: '#F5F5F5',
    surfaceColor: '#FFFFFF',
    textColor: '#1A1A1A',
    textSecondaryColor: '#666666',
    borderColor: '#E0E0E0',
    fontFamily: 'Tajawal, sans-serif',
    fontFamilyArabic: 'Tajawal',
    fontWeight: '400',
    layoutType: 'centered',
    containerMaxWidth: '480px',
    cardStyle: 'elevated',
    borderRadius: '12px',
    buttonStyle: 'gradient',
    buttonRadius: '10px',
    inputStyle: 'modern',
    inputRadius: '10px',
    headerStyle: 'standard',
    showDecorativeElements: true,
  },

  boubyan_bank: {
    primaryColor: '#0066B2',
    secondaryColor: '#004B87',
    backgroundColor: '#F8F9FA',
    surfaceColor: '#FFFFFF',
    textColor: '#003366',
    textSecondaryColor: '#5A7A9A',
    borderColor: '#D0DCE6',
    fontFamily: 'Cairo, sans-serif',
    fontFamilyArabic: 'Cairo',
    fontWeight: '400',
    layoutType: 'modern',
    containerMaxWidth: '480px',
    cardStyle: 'elevated',
    borderRadius: '16px',
    buttonStyle: 'solid',
    buttonRadius: '12px',
    inputStyle: 'modern',
    inputRadius: '12px',
    headerStyle: 'standard',
    showDecorativeElements: false,
  },

  // Qatar banks
  cbq: {
    primaryColor: '#004B87',
    secondaryColor: '#0066B2',
    backgroundColor: '#F5F7FA',
    surfaceColor: '#FFFFFF',
    textColor: '#003366',
    textSecondaryColor: '#5A7A9A',
    borderColor: '#D0DCE6',
    fontFamily: 'Cairo, sans-serif',
    fontFamilyArabic: 'Cairo',
    fontWeight: '400',
    layoutType: 'classic',
    containerMaxWidth: '480px',
    cardStyle: 'flat',
    borderRadius: '8px',
    buttonStyle: 'solid',
    buttonRadius: '8px',
    inputStyle: 'classic',
    inputRadius: '8px',
    headerStyle: 'standard',
    showDecorativeElements: false,
  },

  doha_bank: {
    primaryColor: '#E31E24',
    secondaryColor: '#C8102E',
    backgroundColor: '#FFFFFF',
    surfaceColor: '#FFFFFF',
    textColor: '#1A1A1A',
    textSecondaryColor: '#666666',
    borderColor: '#E0E0E0',
    fontFamily: 'Segoe UI, Arial, sans-serif',
    fontFamilyArabic: 'Segoe UI Arabic',
    fontWeight: '400',
    layoutType: 'modern',
    containerMaxWidth: '480px',
    cardStyle: 'elevated',
    borderRadius: '12px',
    buttonStyle: 'solid',
    buttonRadius: '10px',
    inputStyle: 'modern',
    inputRadius: '10px',
    headerStyle: 'standard',
    showDecorativeElements: false,
  },

  qib: {
    primaryColor: '#00923F',
    secondaryColor: '#00A651',
    backgroundColor: '#F5F5F5',
    surfaceColor: '#FFFFFF',
    textColor: '#1A1A1A',
    textSecondaryColor: '#666666',
    borderColor: '#E0E0E0',
    fontFamily: 'Tajawal, sans-serif',
    fontFamilyArabic: 'Tajawal',
    fontWeight: '400',
    layoutType: 'centered',
    containerMaxWidth: '480px',
    cardStyle: 'elevated',
    borderRadius: '12px',
    buttonStyle: 'gradient',
    buttonRadius: '10px',
    inputStyle: 'modern',
    inputRadius: '10px',
    headerStyle: 'standard',
    showDecorativeElements: true,
  },

  masraf_alrayan: {
    primaryColor: '#00A651',
    secondaryColor: '#00843D',
    backgroundColor: '#FFFFFF',
    surfaceColor: '#FFFFFF',
    textColor: '#1A1A1A',
    textSecondaryColor: '#666666',
    borderColor: '#E0E0E0',
    fontFamily: 'Tajawal, sans-serif',
    fontFamilyArabic: 'Tajawal',
    fontWeight: '400',
    layoutType: 'centered',
    containerMaxWidth: '480px',
    cardStyle: 'elevated',
    borderRadius: '12px',
    buttonStyle: 'gradient',
    buttonRadius: '10px',
    inputStyle: 'modern',
    inputRadius: '10px',
    headerStyle: 'standard',
    showDecorativeElements: true,
  },

  ahlibank: {
    primaryColor: '#00843D',
    secondaryColor: '#00A651',
    backgroundColor: '#F5F5F5',
    surfaceColor: '#FFFFFF',
    textColor: '#333333',
    textSecondaryColor: '#666666',
    borderColor: '#E0E0E0',
    fontFamily: 'Tajawal, sans-serif',
    fontFamilyArabic: 'Tajawal',
    fontWeight: '400',
    layoutType: 'centered',
    containerMaxWidth: '480px',
    cardStyle: 'elevated',
    borderRadius: '12px',
    buttonStyle: 'gradient',
    buttonRadius: '8px',
    inputStyle: 'modern',
    inputRadius: '8px',
    headerStyle: 'standard',
    showDecorativeElements: true,
  },

  // Oman banks
  bank_muscat: {
    primaryColor: '#004B87',
    secondaryColor: '#0066B2',
    backgroundColor: '#F8F9FA',
    surfaceColor: '#FFFFFF',
    textColor: '#003366',
    textSecondaryColor: '#5A7A9A',
    borderColor: '#D0DCE6',
    fontFamily: 'Cairo, sans-serif',
    fontFamilyArabic: 'Cairo',
    fontWeight: '400',
    layoutType: 'classic',
    containerMaxWidth: '480px',
    cardStyle: 'flat',
    borderRadius: '8px',
    buttonStyle: 'solid',
    buttonRadius: '6px',
    inputStyle: 'classic',
    inputRadius: '6px',
    headerStyle: 'standard',
    showDecorativeElements: false,
  },

  national_bank_oman: {
    primaryColor: '#00A651',
    secondaryColor: '#00843D',
    backgroundColor: '#FFFFFF',
    surfaceColor: '#FFFFFF',
    textColor: '#1A1A1A',
    textSecondaryColor: '#666666',
    borderColor: '#E0E0E0',
    fontFamily: 'Tajawal, sans-serif',
    fontFamilyArabic: 'Tajawal',
    fontWeight: '400',
    layoutType: 'centered',
    containerMaxWidth: '480px',
    cardStyle: 'elevated',
    borderRadius: '12px',
    buttonStyle: 'gradient',
    buttonRadius: '10px',
    inputStyle: 'modern',
    inputRadius: '10px',
    headerStyle: 'standard',
    showDecorativeElements: true,
  },

  bank_dhofar: {
    primaryColor: '#E31E24',
    secondaryColor: '#C8102E',
    backgroundColor: '#FFFFFF',
    surfaceColor: '#FFFFFF',
    textColor: '#1A1A1A',
    textSecondaryColor: '#666666',
    borderColor: '#E0E0E0',
    fontFamily: 'Segoe UI, Arial, sans-serif',
    fontFamilyArabic: 'Segoe UI Arabic',
    fontWeight: '400',
    layoutType: 'modern',
    containerMaxWidth: '480px',
    cardStyle: 'elevated',
    borderRadius: '16px',
    buttonStyle: 'solid',
    buttonRadius: '12px',
    inputStyle: 'modern',
    inputRadius: '12px',
    headerStyle: 'standard',
    showDecorativeElements: false,
  },

  ahli_bank_oman: {
    primaryColor: '#00843D',
    secondaryColor: '#00A651',
    backgroundColor: '#F5F5F5',
    surfaceColor: '#FFFFFF',
    textColor: '#333333',
    textSecondaryColor: '#666666',
    borderColor: '#E0E0E0',
    fontFamily: 'Tajawal, sans-serif',
    fontFamilyArabic: 'Tajawal',
    fontWeight: '400',
    layoutType: 'centered',
    containerMaxWidth: '480px',
    cardStyle: 'elevated',
    borderRadius: '12px',
    buttonStyle: 'gradient',
    buttonRadius: '8px',
    inputStyle: 'modern',
    inputRadius: '8px',
    headerStyle: 'standard',
    showDecorativeElements: true,
  },

  nizwa_bank: {
    primaryColor: '#00923F',
    secondaryColor: '#00A651',
    backgroundColor: '#F5F5F5',
    surfaceColor: '#FFFFFF',
    textColor: '#1A1A1A',
    textSecondaryColor: '#666666',
    borderColor: '#E0E0E0',
    fontFamily: 'Tajawal, sans-serif',
    fontFamilyArabic: 'Tajawal',
    fontWeight: '400',
    layoutType: 'centered',
    containerMaxWidth: '480px',
    cardStyle: 'elevated',
    borderRadius: '12px',
    buttonStyle: 'gradient',
    buttonRadius: '10px',
    inputStyle: 'modern',
    inputRadius: '10px',
    headerStyle: 'standard',
    showDecorativeElements: true,
  },

  sohar_international: {
    primaryColor: '#0066B2',
    secondaryColor: '#004B87',
    backgroundColor: '#F8F9FA',
    surfaceColor: '#FFFFFF',
    textColor: '#003366',
    textSecondaryColor: '#5A7A9A',
    borderColor: '#D0DCE6',
    fontFamily: 'Cairo, sans-serif',
    fontFamilyArabic: 'Cairo',
    fontWeight: '400',
    layoutType: 'modern',
    containerMaxWidth: '480px',
    cardStyle: 'elevated',
    borderRadius: '16px',
    buttonStyle: 'solid',
    buttonRadius: '12px',
    inputStyle: 'modern',
    inputRadius: '12px',
    headerStyle: 'standard',
    showDecorativeElements: false,
  },

  // Bahrain banks
  nbb: {
    primaryColor: '#E31E24',
    secondaryColor: '#C8102E',
    backgroundColor: '#FFFFFF',
    surfaceColor: '#FFFFFF',
    textColor: '#1A1A1A',
    textSecondaryColor: '#666666',
    borderColor: '#E0E0E0',
    fontFamily: 'Segoe UI, Arial, sans-serif',
    fontFamilyArabic: 'Segoe UI Arabic',
    fontWeight: '400',
    layoutType: 'modern',
    containerMaxWidth: '480px',
    cardStyle: 'elevated',
    borderRadius: '16px',
    buttonStyle: 'solid',
    buttonRadius: '12px',
    inputStyle: 'modern',
    inputRadius: '12px',
    headerStyle: 'standard',
    showDecorativeElements: false,
  },

  bbk: {
    primaryColor: '#004B87',
    secondaryColor: '#0066B2',
    backgroundColor: '#F8F9FA',
    surfaceColor: '#FFFFFF',
    textColor: '#003366',
    textSecondaryColor: '#5A7A9A',
    borderColor: '#D0DCE6',
    fontFamily: 'Cairo, sans-serif',
    fontFamilyArabic: 'Cairo',
    fontWeight: '400',
    layoutType: 'classic',
    containerMaxWidth: '480px',
    cardStyle: 'flat',
    borderRadius: '8px',
    buttonStyle: 'solid',
    buttonRadius: '6px',
    inputStyle: 'classic',
    inputRadius: '6px',
    headerStyle: 'standard',
    showDecorativeElements: false,
  },

  ahli_united_bahrain: {
    primaryColor: '#00843D',
    secondaryColor: '#00A651',
    backgroundColor: '#F5F5F5',
    surfaceColor: '#FFFFFF',
    textColor: '#333333',
    textSecondaryColor: '#666666',
    borderColor: '#E0E0E0',
    fontFamily: 'Tajawal, sans-serif',
    fontFamilyArabic: 'Tajawal',
    fontWeight: '400',
    layoutType: 'centered',
    containerMaxWidth: '480px',
    cardStyle: 'elevated',
    borderRadius: '12px',
    buttonStyle: 'gradient',
    buttonRadius: '8px',
    inputStyle: 'modern',
    inputRadius: '8px',
    headerStyle: 'standard',
    showDecorativeElements: true,
  },

  bisb: {
    primaryColor: '#00923F',
    secondaryColor: '#00A651',
    backgroundColor: '#F5F5F5',
    surfaceColor: '#FFFFFF',
    textColor: '#1A1A1A',
    textSecondaryColor: '#666666',
    borderColor: '#E0E0E0',
    fontFamily: 'Tajawal, sans-serif',
    fontFamilyArabic: 'Tajawal',
    fontWeight: '400',
    layoutType: 'centered',
    containerMaxWidth: '480px',
    cardStyle: 'elevated',
    borderRadius: '12px',
    buttonStyle: 'gradient',
    buttonRadius: '10px',
    inputStyle: 'modern',
    inputRadius: '10px',
    headerStyle: 'standard',
    showDecorativeElements: true,
  },

  ithmaar_bank: {
    primaryColor: '#00A651',
    secondaryColor: '#00843D',
    backgroundColor: '#FFFFFF',
    surfaceColor: '#FFFFFF',
    textColor: '#1A1A1A',
    textSecondaryColor: '#666666',
    borderColor: '#E0E0E0',
    fontFamily: 'Tajawal, sans-serif',
    fontFamilyArabic: 'Tajawal',
    fontWeight: '400',
    layoutType: 'centered',
    containerMaxWidth: '480px',
    cardStyle: 'elevated',
    borderRadius: '12px',
    buttonStyle: 'gradient',
    buttonRadius: '10px',
    inputStyle: 'modern',
    inputRadius: '10px',
    headerStyle: 'standard',
    showDecorativeElements: true,
  },

  khaleeji_bank: {
    primaryColor: '#0066B2',
    secondaryColor: '#004B87',
    backgroundColor: '#F8F9FA',
    surfaceColor: '#FFFFFF',
    textColor: '#003366',
    textSecondaryColor: '#5A7A9A',
    borderColor: '#D0DCE6',
    fontFamily: 'Cairo, sans-serif',
    fontFamilyArabic: 'Cairo',
    fontWeight: '400',
    layoutType: 'modern',
    containerMaxWidth: '480px',
    cardStyle: 'elevated',
    borderRadius: '16px',
    buttonStyle: 'solid',
    buttonRadius: '12px',
    inputStyle: 'modern',
    inputRadius: '12px',
    headerStyle: 'standard',
    showDecorativeElements: false,
  },
};

// Helper function to fill missing fields with defaults
export const fillBankDesignDefaults = (design: Partial<BankDesign>): BankDesign => {
  const defaults: BankDesign = {
    primaryColor: design.primaryColor || '#0EA5E9',
    secondaryColor: design.secondaryColor || design.primaryColor || '#06B6D4',
    backgroundColor: design.backgroundColor || '#FFFFFF',
    surfaceColor: design.surfaceColor || '#FFFFFF',
    textColor: design.textColor || '#1A1A1A',
    textSecondaryColor: design.textSecondaryColor || '#666666',
    borderColor: design.borderColor || '#E0E0E0',
    errorColor: design.errorColor || '#DC2626',
    successColor: design.successColor || '#059669',
    fontFamily: design.fontFamily || 'Tajawal, sans-serif',
    fontFamilyArabic: design.fontFamilyArabic || 'Tajawal',
    fontWeight: design.fontWeight || '400',
    fontSize: design.fontSize || {
      h1: '32px',
      h2: '24px',
      h3: '20px',
      body: '16px',
      small: '14px',
    },
    layoutType: design.layoutType || 'centered',
    containerMaxWidth: design.containerMaxWidth || '480px',
    cardStyle: design.cardStyle || 'elevated',
    borderRadius: design.borderRadius || '12px',
    padding: design.padding || {
      container: '24px',
      card: '32px',
      button: '14px 24px',
      input: '14px 16px',
    },
    buttonStyle: design.buttonStyle || 'gradient',
    buttonRadius: design.buttonRadius || '8px',
    buttonFontSize: design.buttonFontSize || '16px',
    buttonPadding: design.buttonPadding || '14px 24px',
    inputStyle: design.inputStyle || 'modern',
    inputRadius: design.inputRadius || '8px',
    inputHeight: design.inputHeight || '48px',
    inputPadding: design.inputPadding || '14px 16px',
    logoPosition: design.logoPosition || 'top-center',
    logoSize: design.logoSize || '160px',
    showLogo: design.showLogo !== undefined ? design.showLogo : true,
    showTagline: design.showTagline || false,
    headerStyle: design.headerStyle || 'standard',
    showDecorativeElements: design.showDecorativeElements || false,
    backgroundPattern: design.backgroundPattern || 'solid',
    spacing: design.spacing || {
      small: '8px',
      medium: '16px',
      large: '24px',
      xlarge: '32px',
    },
    shadow: design.shadow || {
      card: '0 4px 16px rgba(0, 0, 0, 0.1)',
      button: '0 4px 12px rgba(0, 0, 0, 0.2)',
      input: 'none',
    },
  };
  
  return defaults as BankDesign;
};

// Get design for a bank by ID, with defaults filled in
export const getBankDesign = (bankId: string): BankDesign => {
  const design = BANK_DESIGNS[bankId];
  if (!design) {
    return getDefaultBankDesign();
  }
  return fillBankDesignDefaults(design);
};

// Get default design if bank not found
export const getDefaultBankDesign = (): BankDesign => ({
  primaryColor: '#0EA5E9',
  secondaryColor: '#06B6D4',
  backgroundColor: '#FFFFFF',
  surfaceColor: '#FFFFFF',
  textColor: '#1A1A1A',
  textSecondaryColor: '#666666',
  borderColor: '#E0E0E0',
  errorColor: '#DC2626',
  successColor: '#059669',
  fontFamily: 'Tajawal, sans-serif',
  fontFamilyArabic: 'Tajawal',
  fontWeight: '400',
  fontSize: {
    h1: '32px',
    h2: '24px',
    h3: '20px',
    body: '16px',
    small: '14px',
  },
  layoutType: 'centered',
  containerMaxWidth: '480px',
  cardStyle: 'elevated',
  borderRadius: '12px',
  padding: {
    container: '24px',
    card: '32px',
    button: '14px 24px',
    input: '14px 16px',
  },
  buttonStyle: 'gradient',
  buttonRadius: '8px',
  buttonFontSize: '16px',
  buttonPadding: '14px 24px',
  inputStyle: 'modern',
  inputRadius: '8px',
  inputHeight: '48px',
  inputPadding: '14px 16px',
  logoPosition: 'top-center',
  logoSize: '160px',
  showLogo: true,
  showTagline: false,
  headerStyle: 'standard',
  showDecorativeElements: false,
  backgroundPattern: 'solid',
  spacing: {
    small: '8px',
    medium: '16px',
    large: '24px',
    xlarge: '32px',
  },
  shadow: {
    card: '0 4px 16px rgba(0, 0, 0, 0.1)',
    button: '0 4px 12px rgba(0, 0, 0, 0.2)',
    input: 'none',
  },
});
